### ISSUE TITLE
Renaming to .ts.source causes compilation issue

### ISSUE THREAD

**Issue by nishantkagrawal** [Zoltu/BuildTools.TypeScript.FromReferences#6]
I setup the project and was succesfully able to generate .ts.source and update the .map respectively.

The problem is that import tsmodels = require("models/commonModels"); doesnt work. It doesnt recognize models/commonModels.ts.source. When i create a models/CommonModels.ts manually, it compiles. 

Note that I am using TypeScript 1.4

**Comment by MicahZoltu** [comment]
In the project properties, set the TypeScript compiler to generate declaration files.  Then when you reference `models/commonModels` it will find `commonModels.d.ts` and use that for type checking.  At runtime, it will find `common models.js`.

Please let me know if this doesn't resolve your issue!

**Comment by MicahZoltu** [comment]
It has been a while and I haven't heard back so I am going to close it under the assumption that my previous suggestion resolved the issue.  If not please re-open!
